# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python3 server.py"

[variables]
PYTHONUNBUFFERED = "1"

